FROM golang:1.26.4 AS builder

WORKDIR /go/src/github.com/falcosecurity/falcosidekick
COPY . .

RUN make falcosidekick

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /go/src/github.com/falcosecurity/falcosidekick/falcosidekick /falcosidekick

EXPOSE 2801

ENTRYPOINT ["/falcosidekick"]
